var qbData = [
{'quarterback': 'Russell Wilson', 'team': 'SEA', 'age': '29.3', 'posRank': '1', 'swamiYards': '4754'},
{'quarterback': 'Carson Wentz', 'team': 'PHI', 'age': '25.2', 'posRank': '2', 'swamiYards': '4045'},
{'quarterback': 'Aaron Rodgers', 'team': 'GB', 'age': '34.3', 'posRank': '3', 'swamiYards': '4526'},
{'quarterback': 'Deshaun Watson', 'team': 'HOU', 'age': '22.5', 'posRank': '4', 'swamiYards': '4958'},
{'quarterback': 'Kirk Cousins', 'team': 'MIN', 'age': '29.6', 'posRank': '5', 'swamiYards': '4535'},
{'quarterback': 'Cam Newton', 'team': 'CAR', 'age': '28.9', 'posRank': '6', 'swamiYards': '4496'},
{'quarterback': 'Jared Goff', 'team': 'LAR', 'age': '23.4', 'posRank': '7', 'swamiYards': '3630'},
{'quarterback': 'Jimmy Garoppolo', 'team': 'SF', 'age': '26.4', 'posRank': '8', 'swamiYards': '4921'},
{'quarterback': 'Dak Prescott', 'team': 'DAL', 'age': '24.6', 'posRank': '9', 'swamiYards': '4022'},
{'quarterback': 'Marcus Mariota', 'team': 'TEN', 'age': '24.4', 'posRank': '10', 'swamiYards': '4425'},
{'quarterback': 'Jameis Winston', 'team': 'TB', 'age': '24.2', 'posRank': '11', 'swamiYards': '4645'},
{'quarterback': 'Matthew Stafford', 'team': 'DET', 'age': '30.1', 'posRank': '12', 'swamiYards': '4423'},
{'quarterback': 'Tom Brady', 'team': 'NE', 'age': '40.6', 'posRank': '13', 'swamiYards': '4499'},
{'quarterback': 'Matt Ryan', 'team': 'ATL', 'age': '32.8', 'posRank': '14', 'swamiYards': '4387'},
{'quarterback': 'Drew Brees', 'team': 'NO', 'age': '39.2', 'posRank': '15', 'swamiYards': '4741'},
{'quarterback': 'Derek Carr', 'team': 'OAK', 'age': '27', 'posRank': '16', 'swamiYards': '3798'},
{'quarterback': 'Andrew Luck', 'team': 'IND', 'age': '28.5', 'posRank': '17', 'swamiYards': '4572'},
{'quarterback': 'Patrick Mahomes', 'team': 'KC', 'age': '22.5', 'posRank': '18', 'swamiYards': '3608'},
{'quarterback': 'Baker Mayfield', 'team': 'prospect', 'age': '21.9', 'posRank': '19', 'swamiYards': '0'},
{'quarterback': 'Andy Dalton', 'team': 'CIN', 'age': '30.4', 'posRank': '20', 'swamiYards': '4082'},
{'quarterback': 'Josh Rosen', 'team': 'prospect', 'age': '21.1', 'posRank': '21', 'swamiYards': '0'},
{'quarterback': 'Lamar Jackson', 'team': 'prospect', 'age': '21.2', 'posRank': '22', 'swamiYards': '0'},
{'quarterback': 'Alex Smith', 'team': 'KC', 'age': '33.9', 'posRank': '23', 'swamiYards': '4107'},
{'quarterback': 'Blake Bortles', 'team': 'JAC', 'age': '26.2', 'posRank': '24', 'swamiYards': '4260'},
{'quarterback': 'Tyrod Taylor', 'team': 'CLE', 'age': '28.6', 'posRank': '25', 'swamiYards': '4672'},
{'quarterback': 'Mitchell Trubisky', 'team': 'CHI', 'age': '23.6', 'posRank': '26', 'swamiYards': '3709'},
{'quarterback': 'Sam Darnold', 'team': 'prospect', 'age': '20.8', 'posRank': '27', 'swamiYards': '0'},
{'quarterback': 'Nick Foles', 'team': 'PHI', 'age': '29.2', 'posRank': '28', 'swamiYards': '3860'},
{'quarterback': 'Josh Allen', 'team': 'prospect', 'age': '21.8', 'posRank': '29', 'swamiYards': '0'},
{'quarterback': 'Philip Rivers', 'team': 'LAC', 'age': '36.3', 'posRank': '30', 'swamiYards': '4215'},
{'quarterback': 'Ben Roethlisberger', 'team': 'PIT', 'age': '36.1', 'posRank': '31', 'swamiYards': '4643'},
{'quarterback': 'Case Keenum', 'team': 'DEN', 'age': '30.1', 'posRank': '32', 'swamiYards': '3638'},
{'quarterback': 'Deshone Kizer', 'team': 'GB', 'age': '22.2', 'posRank': '33', 'swamiYards': '3649'},
{'quarterback': 'Ryan Tannehill', 'team': 'MIA', 'age': '29.6', 'posRank': '34', 'swamiYards': '3954'},
{'quarterback': 'Sam Bradford', 'team': 'ARI', 'age': '30.4', 'posRank': '35', 'swamiYards': '4068'},
{'quarterback': 'Eli Manning', 'team': 'NYG', 'age': '37.2', 'posRank': '36', 'swamiYards': '3709'},
{'quarterback': 'Jacoby Brissett', 'team': 'IND', 'age': '25.3', 'posRank': '37', 'swamiYards': '4361'},
{'quarterback': 'Joe Flacco', 'team': 'BAL', 'age': '33.2', 'posRank': '38', 'swamiYards': '4266'},
{'quarterback': 'Teddy Bridgewater', 'team': 'NYJ', 'age': '25.4', 'posRank': '39', 'swamiYards': '4135'},
{'quarterback': 'Josh McCown', 'team': 'NYJ', 'age': '38.7', 'posRank': '40', 'swamiYards': '4085'},
{'quarterback': 'Brett Hundley', 'team': 'GB', 'age': '24.8', 'posRank': '41', 'swamiYards': '3452'},
{'quarterback': 'Mason Rudolph', 'team': 'prospect', 'age': '22.7', 'posRank': '42', 'swamiYards': '0'},
{'quarterback': 'Luke Falk', 'team': 'prospect', 'age': '23.2', 'posRank': '43', 'swamiYards': '0'}
];

var qbHover = [
'Russell Wilson (SEA), Age: 29.3, Proj. Swami Yards: 4754',
'Carson Wentz (PHI), Age: 25.2, Proj. Swami Yards: 4045',
'Aaron Rodgers (GB), Age: 34.3, Proj. Swami Yards: 4526',
'Deshaun Watson (HOU), Age: 22.5, Proj. Swami Yards: 4958',
'Kirk Cousins (MIN), Age: 29.6, Proj. Swami Yards: 4535',
'Cam Newton (CAR), Age: 28.9, Proj. Swami Yards: 4496',
'Jared Goff (LAR), Age: 23.4, Proj. Swami Yards: 3630',
'Jimmy Garoppolo (SF), Age: 26.4, Proj. Swami Yards: 4921',
'Dak Prescott (DAL), Age: 24.6, Proj. Swami Yards: 4022',
'Marcus Mariota (TEN), Age: 24.4, Proj. Swami Yards: 4425',
'Jameis Winston (TB), Age: 24.2, Proj. Swami Yards: 4645',
'Matthew Stafford (DET), Age: 30.1, Proj. Swami Yards: 4423',
'Tom Brady (NE), Age: 40.6, Proj. Swami Yards: 4499',
'Matt Ryan (ATL), Age: 32.8, Proj. Swami Yards: 4387',
'Drew Brees (NO), Age: 39.2, Proj. Swami Yards: 4741',
'Derek Carr (OAK), Age: 27, Proj. Swami Yards: 3798',
'Andrew Luck (IND), Age: 28.5, Proj. Swami Yards: 4572',
'Patrick Mahomes (KC), Age: 22.5, Proj. Swami Yards: 3608',
'Baker Mayfield (prospect), Age: 21.9, Proj. Swami Yards: 0',
'Andy Dalton (CIN), Age: 30.4, Proj. Swami Yards: 4082',
'Josh Rosen (prospect), Age: 21.1, Proj. Swami Yards: 0',
'Lamar Jackson (prospect), Age: 21.2, Proj. Swami Yards: 0',
'Alex Smith (KC), Age: 33.9, Proj. Swami Yards: 4107',
'Blake Bortles (JAC), Age: 26.2, Proj. Swami Yards: 4260',
'Tyrod Taylor (CLE), Age: 28.6, Proj. Swami Yards: 4672',
'Mitchell Trubisky (CHI), Age: 23.6, Proj. Swami Yards: 3709',
'Sam Darnold (prospect), Age: 20.8, Proj. Swami Yards: 0',
'Nick Foles (PHI), Age: 29.2, Proj. Swami Yards: 3860',
'Josh Allen (prospect), Age: 21.8, Proj. Swami Yards: 0',
'Philip Rivers (LAC), Age: 36.3, Proj. Swami Yards: 4215',
'Ben Roethlisberger (PIT), Age: 36.1, Proj. Swami Yards: 4643',
'Case Keenum (DEN), Age: 30.1, Proj. Swami Yards: 3638',
'Deshone Kizer (GB), Age: 22.2, Proj. Swami Yards: 3649',
'Ryan Tannehill (MIA), Age: 29.6, Proj. Swami Yards: 3954',
'Sam Bradford (ARI), Age: 30.4, Proj. Swami Yards: 4068',
'Eli Manning (NYG), Age: 37.2, Proj. Swami Yards: 3709',
'Jacoby Brissett (IND), Age: 25.3, Proj. Swami Yards: 4361',
'Joe Flacco (BAL), Age: 33.2, Proj. Swami Yards: 4266',
'Teddy Bridgewater (NYJ), Age: 25.4, Proj. Swami Yards: 4135',
'Josh McCown (NYJ), Age: 38.7, Proj. Swami Yards: 4085',
'Brett Hundley (GB), Age: 24.8, Proj. Swami Yards: 3452',
'Mason Rudolph (prospect), Age: 22.7, Proj. Swami Yards: 0',
'Luke Falk (prospect), Age: 23.2, Proj. Swami Yards: 0'
];